// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6PirLGjTfP0YFzbpdf-H9XNiADIEh5cs',
    appId: '1:970397575269:web:63298cf06b9ef6bd02be8c',
    messagingSenderId: '970397575269',
    projectId: 'recipes-calculator-73cb4',
    authDomain: 'recipes-calculator-73cb4.firebaseapp.com',
    storageBucket: 'recipes-calculator-73cb4.appspot.com',
    measurementId: 'G-1C494N5W44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7fMMAwNviX84Za3wN3IYgaHwABKxLhGE',
    appId: '1:970397575269:android:897102dca53df8fa02be8c',
    messagingSenderId: '970397575269',
    projectId: 'recipes-calculator-73cb4',
    storageBucket: 'recipes-calculator-73cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSUsRBf1Rg1Lq-9p6yQFGc8-CW22rvIU',
    appId: '1:970397575269:ios:24b982667514565002be8c',
    messagingSenderId: '970397575269',
    projectId: 'recipes-calculator-73cb4',
    storageBucket: 'recipes-calculator-73cb4.appspot.com',
    iosBundleId: 'com.example.recipesCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSUsRBf1Rg1Lq-9p6yQFGc8-CW22rvIU',
    appId: '1:970397575269:ios:9a3f4ef6830456be02be8c',
    messagingSenderId: '970397575269',
    projectId: 'recipes-calculator-73cb4',
    storageBucket: 'recipes-calculator-73cb4.appspot.com',
    iosBundleId: 'com.example.recipesCalculator.RunnerTests',
  );
}
